import type { DemoState, Expense, Project } from '@/lib/demo-types';

export const ACTIVE_PROJECT_ID = 'ttce-2026';
export const TRACKING_TOKEN = 'tk_7R2K9M';

export const initialProjects: Project[] = [
  {
    id: ACTIVE_PROJECT_ID,
    name: 'Trung thu cho em 2026',
    organization: 'Nhóm Nắng Ấm',
    startDate: '12/08/2026',
    endDate: '30/09/2026',
    budget: 50_000_000,
    baseSpent: 31_850_000,
    status: 'active',
    publicEnabled: true,
    submissionsOpen: true,
    pendingCount: 6,
    recordedCount: 34,
    categories: [
      { name: 'Quà tặng trẻ em', total: 18_000_000, spent: 14_200_000, color: '#5f31a8' },
      { name: 'Vận chuyển & hậu cần', total: 10_000_000, spent: 8_300_000, color: '#f49e1b' },
      { name: 'Truyền thông', total: 7_000_000, spent: 3_650_000, color: '#8f6bc5' },
      { name: 'Hoạt động & địa điểm', total: 15_000_000, spent: 5_700_000, color: '#2f7d68' },
    ],
  },
  {
    id: 'dong-am-2026',
    name: 'Đông ấm vùng cao',
    organization: 'Nhóm Nắng Ấm',
    startDate: '01/09/2026',
    endDate: '20/12/2026',
    budget: 72_000_000,
    baseSpent: 12_800_000,
    status: 'active',
    publicEnabled: true,
    submissionsOpen: true,
    pendingCount: 1,
    recordedCount: 28,
    categories: [],
  },
  {
    id: 'sach-cho-em-3',
    name: 'Sách cho em — đợt 3',
    organization: 'Nhóm Nắng Ấm',
    startDate: '15/08/2026',
    endDate: '15/10/2026',
    budget: 15_000_000,
    baseSpent: 0,
    status: 'preparing',
    publicEnabled: false,
    submissionsOpen: false,
    pendingCount: 0,
    recordedCount: 0,
    categories: [],
  },
  {
    id: 'tet-yeu-thuong-2026',
    name: 'Tết yêu thương 2026',
    organization: 'Nhóm Nắng Ấm',
    startDate: '05/01/2026',
    endDate: '28/02/2026',
    budget: 38_000_000,
    baseSpent: 36_500_000,
    status: 'closed',
    publicEnabled: true,
    submissionsOpen: false,
    pendingCount: 0,
    recordedCount: 92,
    categories: [],
  },
  {
    id: 'he-xanh-2026',
    name: 'Hè xanh — Đắk Lắk',
    organization: 'Nhóm Nắng Ấm',
    startDate: '10/06/2026',
    endDate: '05/08/2026',
    budget: 45_000_000,
    baseSpent: 39_700_000,
    status: 'closed',
    publicEnabled: true,
    submissionsOpen: false,
    pendingCount: 0,
    recordedCount: 158,
    categories: [],
  },
];

export const initialExpenses: Expense[] = [
  {
    id: 'UII-0249',
    projectId: ACTIVE_PROJECT_ID,
    title: 'Tập vẽ và bút màu',
    submitter: 'Nguyễn Minh Anh',
    payer: 'Nguyễn Minh Anh',
    amount: 1_250_000,
    date: '28/08/2026',
    time: '18:42',
    category: 'Quà tặng trẻ em',
    fundingSource: 'Quỹ Vì Trẻ Em',
    vendor: 'Nhà sách FAHASA',
    invoiceNumber: 'HD-028491',
    status: 'pending',
    submittedAt: '29/08/2026 · 09:38',
    evidence: ['transfer', 'invoice'],
    items: [
      { name: 'Tập vẽ A4', quantity: 40, unitPrice: 18_000 },
      { name: 'Bút màu 12 cây', quantity: 20, unitPrice: 26_500 },
    ],
    risk: 'budget',
  },
  {
    id: 'UII-0248',
    projectId: ACTIVE_PROJECT_ID,
    title: 'Thuê xe vận chuyển',
    submitter: 'Trần Gia Huy',
    payer: 'Trần Gia Huy',
    amount: 2_800_000,
    date: '28/08/2026',
    time: '15:10',
    category: 'Vận chuyển & hậu cần',
    fundingSource: 'Quỹ vận hành',
    vendor: 'Nhà xe Minh Tâm',
    invoiceNumber: 'PX-8821',
    status: 'pending',
    submittedAt: '28/08/2026 · 16:02',
    evidence: ['transfer'],
    items: [],
    risk: 'duplicate',
  },
  {
    id: 'UII-0247',
    projectId: ACTIVE_PROJECT_ID,
    title: 'Bánh trung thu',
    submitter: 'Lê Thảo Vy',
    payer: 'Lê Thảo Vy',
    amount: 860_000,
    date: '27/08/2026',
    time: '10:16',
    category: 'Quà tặng trẻ em',
    fundingSource: 'Quỹ Vì Trẻ Em',
    vendor: 'Bếp Nhà Mây',
    invoiceNumber: 'BNM-1086',
    status: 'recorded',
    submittedAt: '27/08/2026 · 11:03',
    evidence: ['transfer', 'invoice'],
    items: [{ name: 'Bánh trung thu', quantity: 20, unitPrice: 43_000 }],
    risk: 'none',
  },
  {
    id: 'UII-0241',
    projectId: ACTIVE_PROJECT_ID,
    title: 'Bánh trung thu cho đêm hội',
    submitter: 'Nguyễn Minh Anh',
    payer: 'Nguyễn Minh Anh',
    amount: 4_680_000,
    date: '28/08/2026',
    time: '08:45',
    category: 'Quà tặng trẻ em',
    fundingSource: 'Quỹ Vì Trẻ Em',
    vendor: 'Hỷ Lâm Môn',
    invoiceNumber: 'HLM-2408',
    status: 'pending',
    submittedAt: '28/08/2026 · 09:12',
    evidence: ['transfer', 'invoice'],
    items: [{ name: 'Bánh trung thu thiếu nhi', quantity: 120, unitPrice: 39_000 }],
    risk: 'none',
  },
  {
    id: 'UII-0235',
    projectId: ACTIVE_PROJECT_ID,
    title: 'Thuê loa và âm thanh',
    submitter: 'Nguyễn Minh Anh',
    payer: 'Nguyễn Minh Anh',
    amount: 800_000,
    date: '26/08/2026',
    time: '20:05',
    category: 'Hoạt động & địa điểm',
    fundingSource: 'Quỹ vận hành',
    vendor: 'Âm thanh Thành Công',
    invoiceNumber: '—',
    status: 'needs_more',
    submittedAt: '26/08/2026 · 20:34',
    evidence: ['transfer'],
    items: [],
    note: 'Ảnh bill bị mờ ở phần tổng tiền, bạn chụp lại giúp mình nhé. — Người phụ trách, 27/08',
    risk: 'missing',
  },
  {
    id: 'UII-0228',
    projectId: ACTIVE_PROJECT_ID,
    title: 'In poster sự kiện',
    submitter: 'Nguyễn Minh Anh',
    payer: 'Nguyễn Minh Anh',
    amount: 450_000,
    date: '22/08/2026',
    time: '14:21',
    category: 'Truyền thông',
    fundingSource: 'Quỹ vận hành',
    vendor: 'In Nhanh 24h',
    invoiceNumber: 'IN-220826',
    status: 'recorded',
    submittedAt: '22/08/2026 · 14:40',
    evidence: ['invoice'],
    items: [{ name: 'Poster A2', quantity: 30, unitPrice: 15_000 }],
    risk: 'none',
  },
];

export const initialDemoState: DemoState = {
  projects: initialProjects,
  expenses: initialExpenses,
};

export const money = (value: number) => `${new Intl.NumberFormat('vi-VN').format(value)}₫`;

export const shortMoney = (value: number) => {
  if (value >= 1_000_000) return `${new Intl.NumberFormat('vi-VN', { maximumFractionDigits: 2 }).format(value / 1_000_000)} triệu`;
  return money(value);
};

export const statusLabel = {
  pending: 'Chờ duyệt',
  needs_more: 'Cần bổ sung',
  recorded: 'Đã ghi nhận',
  rejected: 'Đã từ chối',
} as const;
